os: linux
dist: focal

language: php
php:
  - 7.4

before_script:
  - wget "https://github.com/Kxnrl/php-utility/raw/master/KeyValues/KeyValues.php" -q -O KeyValues.php
  - wget "https://github.com/Kxnrl/php-utility/raw/master/Configs/Configs.php" -q -O Configs.php
script:
  - php -f KeyValues.php
  - php -f Configs.php

notifications:
  recipients:
    - kyle@kxnrl.com
    - 1149873216@qq.com
    - 834888744@qq.com
    - 286921966@qq.com
    - 378379682@qq.com
  on_success: never
  on_failure: always
