name: PR Verify

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: morrisoncole/pr-lint-action@v1.6.1
      with:
        title-regex: '^(新增|修改)\:(\ )(ze|mg|ttt|jb|bhop|surf|kz|kzpro|vnl|skz|bkz|xc)\_[a-zA-Z0-9_]+$'
        on-failed-regex-fail-action: true
        on-failed-regex-create-review: true
        on-failed-regex-comment: "无效的PR标题, 请修改为符合手册的规范, 例如: ``修改: mg_abc_v1`` 或 ``新增: mg_abc_v2``"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
