name: PR Verify

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

permissions:
  issues: write
  pull-requests: write

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: fys-csgo/pr-lint-action@main
      with:
        title-regex: '["^(新增|修改|回滚)(ZE|TTT|JB|MG|KZ|Retakes|BHop|Surf|HnS)服务器(配置|参数)\\:\\s\\S+$","^新增地图\\:\\s(ze|mg|ttt|jb|bhop|surf|kz|kzpro|vnl|skz|bkz|xc)\\_[a-zA-Z0-9_]+$","^(修改|回滚|补充)地图(数据|翻译|Boss|关卡|按钮|参数|神器|通关奖励)?\\:\\s(ze|mg|ttt|jb|bhop|surf|kz|kzpro|vnl|skz|bkz|xc)\\_[a-zA-Z0-9_]+$"]'
        on-failed-regex-fail-action: true
        on-failed-regex-create-review: true
        on-failed-regex-comment: "无效的PR标题, 请修改为符合手册的规范, 例如: ``修改: mg_abc_v1`` 或 ``新增: mg_abc_v2``"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
